### ISSUE TITLE
Convene an Identifiers Task Group

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#14] opened 2017-10-05 13:09 UTC
An open call for nominations.
A task group to revise the [GUID applicability statement](http://www.tdwg.org/standards/150)

Nominations from:
@godfoder
@jgerbracht
...

**Comment by chicoreus** [comment] 2017-10-12 19:25
Everyone present on the Tuesday 2017-Oct-03 meeting of the TAG at TDWG 2017 expressed interest in  participating in this task group: Paul Morris, Dimitris Koureas, Jonathan Rees, Dag Endresen, Joel Sachs, Pier Buttigieg, Jeff Gerbracht, Steve Baskauf, Stan Blum.

**Comment by chicoreus** [comment] 2018-08-30 01:57
@dkoureas has agreed to be the convener of this task group, starting January 2018.

**Comment by dhobern** [comment] 2018-08-30 12:00
I'm also interested in participating in this task group.  The GUID AS is not easily found on the portal.  The http://www.tdwg.org/standards/150 link is now https://www.tdwg.org/standards/guid-as/ but the PDF link from there is broken.

**Comment by dkoureas** [comment] 2018-09-04 08:06
Thanks all,

Will invite people who already expressed their interest to join the group
as of January 2019. In the meantime will work with Paul to draft the new
charter of the TG.

Kind regards,
Dimitris

*--*

*Dr Dimitris Koureas, FLS*
*Programme Director - Department Head*
International Biodiversity Infrastructures
Naturalis Biodiversity Center, P.O. Box 9517, 2300 RA Leiden, NL

Coordinator, Distributed System of Scientific Collections (DiSSCo
<http://dissco.eu/>)
Chair, Biodiversity Information Standards Organisation (TDWG
<http://tdwg.org/>)
Research Data Alliance (RDA <http://www.rd-alliance.org/>) - Technical
Advisory Board member

*ORCID*: 0000-0002-4842-6487 | *Linkedin*: linkedin.com/in/dkoureas
*Twitter*: @DimitrisKoureas | *Tel*: +31 (0) 71 751 9251

**Comment by baskaufs** [comment] 2018-09-04 17:13
The link to the GUID AS is https://github.com/tdwg/guid-as/blob/master/guid/tdwg_guid_applicability_statement.pdf . I've submitted a pull request to fix it on the website.

**Comment by jar398** [comment] 2020-04-07 17:30
This effort has been idle, as far as I can tell, for quite a while. What does one do in order to join and participate in the group? Is there any charter or work plan?

**Comment by debpaul** [comment] 2020-04-10 17:40
Hi @jar398 I'm wondering what @stanblum might have to say here. See for example, this ticket https://github.com/tdwg/cd/issues/40 regarding the need for PID system for collections. (We need help in this group to take on that particular issue, and could use your expertise as well as that of others originally interested. This group would also be able to contribute to the work of the [Alliance for Bio](https://www.allianceforbio.org/) .... and others

**Comment by jar398** [comment] 2022-08-29 23:23
Thoughts following on to today's TAG meeting where @baskaufs wanted to know if it could be closed:

I've just done a quick review of the TDWG web site and the 2010 GUID applicability statement and I don't see what the issue is. Up until 2016 there was a statement on the web site saying LSIDs were preferred, and I had complained about it a few times, but that was gone by 2017. Everything seems consistent and acceptable now: the GUID applicability statement looks OK, and the recommendation is to use of one of the systems on the R1 list, which includes both HTTP and LSID. So I'm inclined to say close.

A few people on the TAG call today said they thought LSIDs should be deprecated, but this was not unanimous. Maybe the TG's purpose would just be to discuss this and decide whether such an action is warranted? I have some thoughts (resisting putting them in this issue since they're not on topic).  If this is the only open question maybe we could deal with it in a new github issue instead of creating a TG?

@debpaul The question of identifier strategies for particular efforts or domains should probably be addressed by those particular efforts or domains (such as CD), yes? When we speak of 'identifiers' we do not usually intend to include the design of completely general metadata formats.

The question of persistence often comes up in this context but it never has a technical solution because it is not a technical problem.

Someone thought something needed to be done or this issue wouldn't exist. I was at these meetings but don't remember and unfortunately don't have notes. To make sure I haven't missed anything I must appeal to @dkoureas, @ghwhitbread, or anyone else who might remember.

**Comment by jar398** [comment] 2022-08-31 23:20
Looks like discussion is underway here:
#9 Revise GUID standard
#2 Deprecated LSID recommendation
I can see that what I wrote is largely redundant with what's been discussed under this issues.
It's not clear to me whether the proposed identifiers TG is supposed to cover these and only these issues.

**Comment by baskaufs** [comment] 2022-11-13 21:51
This issue is being closed with further discussion to take place at https://github.com/tdwg/tag/issues/36

**Closed by baskaufs** 2022-11-13 21:51 UTC
Labels: identifiers
